mysite/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    #widoki posta
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Roboczy'
        PUBLISHED = 'PB', 'Opublikowany'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices,
                              default=Status.DRAFT)
    objects = models.Manager()
    tags = TaggableManager()
    published = PublishedManager()
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f"Komentarz dodany przez {self.name} dla posta {self.post}"

mysite/blog/forms.py
from django import forms
from .models import Comment


class SearchForm(forms.Form):
    query = forms.CharField()


class EmailPostsForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

mysite/blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from blog.models import Post, Comment
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostsForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count



# class PostListView(ListView):
#     """"
#     Alternatywny widok listy postów
#     """
#     queryset = Post.objects.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags=tag)
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # Jesli pagenumber nie jest liczba całkowita zwróc pierwsza stronę
        posts = paginator.page(1)
    except EmptyPage:
        # Jesli zmienna pagenumbe jest poza zakresem wyslij ostatnia strone projektów
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    #lista podobnych postów
    post_tags_ids = post.tags.values_list('id', flat=True)
    similiar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similiar_posts = similiar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'form': form,
                                                     'similar_posts': similiar_posts})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, \
                                   status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostsForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'your_account@gmail.com',
                      [cd['to']])
            sent = True

    else:
        form = EmailPostsForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    #opublikowano komentarz
    form = CommentForm(data=request.POST)
    if form.is_valid():
        #utworz obiekt Comment bez zapsywania go w bazie danych
        comment = form.save(commit=False)
        #przypisz post do komentarza
        comment.post = post
        #zapisz post do bazy danych
        comment.save()
    return render(request, 'blog/post/comment.html',
                  {'post': post, 'form': form, 'comment': comment})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),).filter(similarity__gt=0.1).order_by('-similarity')

    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

mysite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
{% load blog_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titile %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <p>
        to mój blog
        Dotychczas opublikowałem {% total_posts %} postów.
    </p>
    <h3> Najnowsze posty </h3>
    {% show_latest_posts 3 %}
    <h3>Najczęściej komentowane posty</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url}}">{{ post.title }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Dodaj komentarz{% endblock %}
{% block content %}
    {% if comment %}
        <h2>Twój komentarz został dodany</h2>
        <p><a href="{{ post.get_absolute_url }}"> Powrót do posta </a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{post.title}}{% endblock %}

{% block content %}
    <h1>{{post.title}}</h1>
    <p class="date">
        Opublikowany {{ post.pulish }} przez {{ post.author }}
    </p>
    {{post.body|markdown}}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Udostępnij post
        </a>
    </p>
    <h2>Podobne posty</h2>
    {% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
    </p>
    {% empty %}
    Nie ma jeszcze podobnych postów
    {% endfor %}
    {% with comments.count as total_comments %}
    <h2>{{ total_comments }} komentarzy</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
        <p class="info">
            Komentarz {{ forloop.counter }} dodany przez {{ comment.name }} {{ comment.created }}
        </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p> nie ma jeszcze zadnych komentarzy. </p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

mysite/blog/templates/blog/post/includes/comment_form.html
<h2>Dodaj nowy komentarz</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
{{ form.as_p }}
{% csrf_token %}
<p><input type="submit" value="Dodaj komentarz"></p>
</form>

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
    </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Mój Blog{% endblock %}

{% block content %}
    <h1> Mój blog</h1>
    {% if tag %}
        <h2>Posty oznaczone tagiem "{{tag.name}}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tagi:
            {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{tag.name}}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Opublikwoany {{ post.publish }} przez {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}Szukaj{% endblock %}

{% block content %}
    {% if query %}
    <h1> Posty zawierające " {{ query }}</h1>
    <h3>
        {% with results.count as total_results %}
        Znaleziono {{ total_results }} wyników
        {% endwith %}
    </h3>
        {% for post in results %}
        <h4>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h4>
        {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
        <p> Brak wyników wyszukiwania </p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}"></a></p>
    {% else %}
    <form method="get">
        {{form.as_p}}
        <input type="submit" value="Szukaj">
    </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %} Udostepnij post {% endblock %}

{% block content %}
    {% if sent %}
    <h1> Wiadomośc e-mail została pomyślnie wysłana</h1>
    <p>
        "Wysłanie posta {{ post.title }}" do {{ form.cleaned_data.to}}
        zakończyło się sukcesem
    </p>
    {% else %}
    <h1> Udostępnij "{{ post.title }}" przez e-mail</h1>
    <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="Wyślij wiadomość e-mail">
    </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <span class="current">
            Strona {{ page.number}} z {{ page.paginator.num_pages }} .
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}"> Następna </a>
        {% endif %}
    </span>
</div>